#### CONFIG FILE FOR SilverTorch V0.1 ####
# All Configuration KEYS MUST be filled FOR NOW

# can be firepower only right now. Palo_Alto will be coming in further releases if possible :)
firewall_type: firepower

# can be set to None if the device IS NOT MANAGED from a central controller
management_center: 10.11.6.60

#/ the following is needed for firepower suite
access_policy: test_acp
domain: Global
#\

# the firewall to make routing and interface reference from FOR now a sample of ONE is supported.
firewall_sensor: 10.11.6.191
# when pushing a config this will be prepended to the new rules, \
# in addition if other functions such as cleanup or checkup is used it will find rules in the ruleset with this specific \
# name in the rule name BUT *BE AS CONCISE AS POSSIBLE.*
rule_prepend_name: VOIP_RULES
# if there is not a routing entry for a specific IP in the IPPP then use this zone to set its zone in the ruleset.
zone_of_last_resort: outside_zone

ippp_location: gfrs.csv
# if don't want to use the routing information from the firewall, and you have already a IP-to-ZONE matrix insert the file name.
zone_based_routing_bypass: false
# whether the controller and the firewall/sensor uses the same creds.
same_creds: true
# CAN ONLY BE ALLOW OR DENY FOR RULE ENTRY
ruleset_type: ALLOW
# APPENDED COMMENT TO RULES
rule_comment: None

#/ TEST SECTION
# check to see if IPPP exist in the firewalls ruleset
ippp_checkup: false
#\ TEST SECTION

#/ CLEAN UP SECTION
cleanup: false
# if there are rules that you want to collapse/reorganize for firewall scaffolding.
rule_cleanup: false
# if you want change the name of host objects to there DNS or IP attributes.
object_cleanup: false
# whether you want IP or DNS as the new name value for object cleanup ACCEPTABLES: resolve|ip
clean_type: resolve
#\ CLEAN UP SECTION

# emergency switch in case something happened(network/power drop) in rule cleanup module since it involved rearranges the firewall configs.
# this switch will reinstall the ACP ruleset that were modified.
# recover old ACP file if the program crashed
recovery_mode: false
# if you want to use the ACTUAL PROTOCOL:PORT pair instead of the port defined name you can enable strict checking
strict_checkup: true
# if you want objects in the firewall to have DNS resolved local hostnames instead of IPs as the object name, enable this
# you can also filter on what domain you just want the hostname for in dont_include_domains
resolve_objects: false
# This will by REGEX
dont_include_domains: 'com|org'



##### only used if you have FilMoreBlanks installed ######
fill_csv_blanks: true

# the key item should be the OLD value in the CSV to look for, while the value item should be what you want to change it
# to. ALSO, the Value item HAS TO A BE LIST Object as one of the object displayed below
change_list:
  new servers: ['5,5,5,5','2.2.2.2','7,7,7,7']
  11.1.0.0/16:
    - "233.31.244.39"
    - "100.19.68.193"
    - '235.253.243.128'
    - '232.151.66.30'
    - '74.22.1.140'
  169.156.158.231: ['111.254.29.134','96.20.144.254']

# if only a particular set of columns are needed, match the key item from the change_list to the columns to only want
# affected. this can be list or a string object.
affect_only_columns:
      11.1.0.0/16: 'source'
